//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0de73ede_656e_4c64_b95c_26b2b39a07ae {
            get {
                object obj = ResourceManager.GetObject("0de73ede-656e-4c64-b95c-26b2b39a07ae", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6460f2cb_b69f_4975_bff7_655f81aee4bb {
            get {
                object obj = ResourceManager.GetObject("6460f2cb-b69f-4975-bff7-655f81aee4bb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _716c17e3_5e69_4933_8d90_53d5b8a64fb2 {
            get {
                object obj = ResourceManager.GetObject("716c17e3-5e69-4933-8d90-53d5b8a64fb2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_cartoon_illustration_depicting_the_interior_of_a_modern_pharmacy_with_shelves_filled_with_various_medications_a_counter_and_a_waiting_area_free_vector {
            get {
                object obj = ResourceManager.GetObject("a-cartoon-illustration-depicting-the-interior-of-a-modern-pharmacy-with-shelves-f" +
                        "illed-with-various-medications-a-counter-and-a-waiting-area-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_cartoon_illustration_depicting_the_interior_of_a_modern_pharmacy_with_shelves_filled_with_various_medications_a_counter_and_a_waiting_area_free_vector1 {
            get {
                object obj = ResourceManager.GetObject("a-cartoon-illustration-depicting-the-interior-of-a-modern-pharmacy-with-shelves-f" +
                        "illed-with-various-medications-a-counter-and-a-waiting-area-free-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_cartoon_illustration_depicting_the_interior_of_a_modern_pharmacy_with_shelves_filled_with_various_medications_a_counter_and_a_waiting_area_free_vector2 {
            get {
                object obj = ResourceManager.GetObject("a-cartoon-illustration-depicting-the-interior-of-a-modern-pharmacy-with-shelves-f" +
                        "illed-with-various-medications-a-counter-and-a-waiting-area-free-vector2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a25497ff5850016882a25465a8b5bb03 {
            get {
                object obj = ResourceManager.GetObject("a25497ff5850016882a25465a8b5bb03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b7fb22ed_6c36_4a5d_8035_33ae5a099954 {
            get {
                object obj = ResourceManager.GetObject("b7fb22ed-6c36-4a5d-8035-33ae5a099954", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bbf7efd48e6c7bb9432400b723612864 {
            get {
                object obj = ResourceManager.GetObject("bbf7efd48e6c7bb9432400b723612864", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_19_56_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_19_56 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_27_49_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_27_49 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_43_07_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_43_07 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_46_18_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_46_18 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_46_18_a_m1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_46_18 a.m1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_4_may_2026__08_53_12_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 4 may 2026, 08_53_12 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_5_may_2026__01_28_00_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 5 may 2026, 01_28_00 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_5_may_2026__02_43_56_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 5 may 2026, 02_43_56 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_5_may_2026__08_51_55_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 5 may 2026, 08_51_55 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_6_may_2026__01_28_00_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 6 may 2026, 01_28_00 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_6_may_2026__08_51_55_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 6 may 2026, 08_51_55 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_7_may_2026__01_28_00_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 7 may 2026, 01_28_00 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_7_may_2026__08_51_55_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 7 may 2026, 08_51_55 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_8_may_2026__01_28_00_p_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 8 may 2026, 01_28_00 p.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d12ec261_1830_4611_beb9_985ee7aab672 {
            get {
                object obj = ResourceManager.GetObject("d12ec261-1830-4611-beb9-985ee7aab672", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d59f8ab0fd0143bd404d422cd51ad3d7 {
            get {
                object obj = ResourceManager.GetObject("d59f8ab0fd0143bd404d422cd51ad3d7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d78a193f_64c3_4a38_8783_c0338b0317c0 {
            get {
                object obj = ResourceManager.GetObject("d78a193f-64c3-4a38-8783-c0338b0317c0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga {
            get {
                object obj = ResourceManager.GetObject("descarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga__1_ {
            get {
                object obj = ResourceManager.GetObject("descarga (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_button_login_image_file_formats_logo {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-button-login-image-file-formats-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_magnifying_glass_magnifier_symbol_magnifying_glass_text_magnifier {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-magnifying-glass-magnifier-symbol-magnifying-glass-tex" +
                        "t-magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_magnifying_glass_magnifier_symbol_magnifying_glass_text_magnifier1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-magnifying-glass-magnifier-symbol-magnifying-glass-tex" +
                        "t-magnifier1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_user_login_icon_design_media_area_user_symbol {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-user-login-icon-design-media-area-user-symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
